-- owo_roles
CREATE TABLE IF NOT EXISTS owo_roles
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE=InnoDB;


-- owo_users
CREATE TABLE IF NOT EXISTS owo_users
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(300) NOT NULL UNIQUE,
    password VARCHAR(1000) NOT NULL,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(300) NOT NULL UNIQUE,
    phone VARCHAR(50) NULL DEFAULT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    email_token VARCHAR(50) NULL DEFAULT NULL,
    email_verified BOOLEAN DEFAULT FALSE,
    email_verified_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    role_id BIGINT NULL DEFAULT NULL,
    CONSTRAINT fk_owo_users_role_id FOREIGN KEY (role_id) REFERENCES owo_roles(id)
)
ENGINE=InnoDB;


-- owo_articles
CREATE TABLE IF NOT EXISTS owo_articles
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(300) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_owo_articles_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;


-- owo_tokens
CREATE TABLE IF NOT EXISTS owo_tokens
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    token VARCHAR(100) NOT NULL UNIQUE,
    lifetime BIGINT NULL DEFAULT NULL,
    claimer VARCHAR(1000) NULL DEFAULT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    is_revoked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_owo_tokens_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;


-- owo_clients
CREATE TABLE IF NOT EXISTS owo_clients
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    pkey VARCHAR(300) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    secret VARCHAR(500) NULL DEFAULT NULL,
    origin_uris VARCHAR(3000) NULL DEFAULT NULL,
    redirect_uris VARCHAR(3000) NULL DEFAULT NULL,
    grant_types VARCHAR(300) NULL DEFAULT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_oauth_clients_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;


-- owo_providers
CREATE TABLE IF NOT EXISTS owo_providers
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    authorization_endpoint VARCHAR(3000) NOT NULL,
    token_endpoint VARCHAR(3000) NOT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    client_public_key VARCHAR(300) NOT NULL,
    client_secret VARCHAR(500) NULL DEFAULT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_oauth_providers_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;


-- owo_access_tokens
CREATE TABLE IF NOT EXISTS owo_access_tokens
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    access_token VARCHAR(500) NOT NULL UNIQUE,
    refresh_token VARCHAR(500) NULL DEFAULT NULL,
    token_type VARCHAR(50) NULL DEFAULT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    expires_in BIGINT NULL DEFAULT NULL,
    issued_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    provider_id BIGINT NULL DEFAULT NULL,
    client_id BIGINT NOT NULL,
    user_id BIGINT NULL DEFAULT NULL,
    CONSTRAINT fk_oauth_access_tokens_provider_id FOREIGN KEY (provider_id) REFERENCES owo_providers(id),
    CONSTRAINT fk_oauth_access_tokens_client_id FOREIGN KEY (client_id) REFERENCES owo_clients(id),
    CONSTRAINT fk_oauth_access_tokens_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;


-- owo_authorization_codes
CREATE TABLE IF NOT EXISTS owo_authorization_codes
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    authorization_code VARCHAR(100) NOT NULL UNIQUE,
    challenge VARCHAR(300) NULL DEFAULT NULL,
    challenge_method VARCHAR(100) NULL DEFAULT NULL,
    redirect_uri VARCHAR(3000) NULL DEFAULT NULL,
    expires_in BIGINT NOT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    token_id BIGINT NULL DEFAULT NULL,
    client_id BIGINT NOT NULL,
    user_id BIGINT NULL DEFAULT NULL,
    CONSTRAINT fk_oauth_authorization_codes_token_id FOREIGN KEY (token_id) REFERENCES owo_access_tokens(id),
    CONSTRAINT fk_oauth_authorization_codes_client_id FOREIGN KEY (client_id) REFERENCES owo_clients(id),
    CONSTRAINT fk_oauth_authorization_codes_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;


-- owo_refresh_tokens
CREATE TABLE IF NOT EXISTS owo_refresh_tokens
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    refresh_token VARCHAR(500) NOT NULL UNIQUE,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    expires_in TIMESTAMP NOT NULL,
    issued_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    client_id BIGINT NOT NULL,
    user_id BIGINT NULL DEFAULT NULL,
    CONSTRAINT fk_oauth_refresh_tokens_client_id FOREIGN KEY (client_id) REFERENCES owo_clients(id),
    CONSTRAINT fk_oauth_refresh_tokens_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;


-- owo_scopes
CREATE TABLE IF NOT EXISTS owo_scopes
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE=InnoDB;


-- owo_jwts
CREATE TABLE IF NOT EXISTS owo_jwts
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    subject VARCHAR(500) NULL DEFAULT NULL UNIQUE,
    public_key VARCHAR(3000) NOT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    client_id BIGINT NOT NULL,
    user_id BIGINT NULL DEFAULT NULL,
    CONSTRAINT fk_oauth_jwts_client_id FOREIGN KEY (client_id) REFERENCES owo_clients(id),
    CONSTRAINT fk_oauth_jwts_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;


-- owo_alerts
CREATE TABLE IF NOT EXISTS owo_alerts
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(50) NOT NULL,
    message VARCHAR(500) NOT NULL,
    scope VARCHAR(5000) NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_owo_alerts_user_id FOREIGN KEY (user_id) REFERENCES owo_users(id)
)
ENGINE=InnoDB;
